function parseError(error) {
    if (error.name == 'ValidationError') {

        return Object.values(error.errors).map(v => v.message); //mongoose error
    } else if (Array.isArray(error)) {

        return error.map(x => x.msg); //validator errors
    } else {

        return error.message.split('\n'); //error generated by throw new Error syntax
    }
}

module.exports = {
    parseError
}